### ISSUE TITLE
ImportError: cannot import name 'ElkanotoPuClassifier

### ISSUE THREAD

**Issue by lucy9383** [pulearn/pulearn#10]
#9 

Hi,

I update the package to 0.0.7 version but still find that I cannot import the classifier.  I tried to run it both through cmd and Pycharm.

The error itself looks like this:

Traceback (most recent call last):
  File "C:\Users\dd\Desktop\pulearn.py", line 8, in <module>
    from pulearn import (
  File "C:\Users\dd\Desktop\pulearn.py", line 8, in <module>
    from pulearn import (
ImportError: cannot import name 'ElkanotoPuClassifier'

I run the debugger in Pycharm.  It shows:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\dd\Desktop\pulearn.py", line 8, in <module>
    from pulearn import (
ImportError: cannot import name 'ElkanotoPuClassifier'

I tried to google but did not a solution.  I am wondering if I miss something here.  Thanks!

**Comment by shaypal5** [comment]
Well, I don't think it's specifically related to this package.
As you can see imports of the ``ElkanotoPuClassifier`` class work perfectly in all tests.
The package is throughly tested on Python 3.5 to 3.8, Linux, macOS and Windows, and even Python dev branches,

Maybe this has something to do with how you installed the package or how you setup the Python environment you are using?

**Comment by lucy9383** [comment]
> Well, I don't think it's specifically related to this package.
> As you can see imports of the `ElkanotoPuClassifier` class work perfectly in all tests.
> The package is throughly tested on Python 3.5 to 3.8, Linux, macOS and Windows, and even Python dev branches,
> 
> Maybe this has something to do with how you installed the package or how you setup the Python environment you are using?

Thanks for the reply:)

I do not see the specific point related to this package...  But my other packages work well and I tried to uninstall and reinstall it several times.  I just checked the directory of the package: C:\Users\dd\AppData\Local\Programs\Python\Python36\Lib\site-packages

Is it the right place to install the package?

**Comment by shaypal5** [comment]
Yeah, it's where Python packages normally go to.

**Comment by shaypal5** [comment]
I'm closing this for now. Please reopen if you indeed think it's related to this package specifically, and we'll work this through.
