### ISSUE TITLE
How do I save and load this PU_bagging model?

### ISSUE THREAD

**Issue by tw200464tw** [pulearn/pulearn#14]
Now I have completed the training of the PU_bagging model,but I  can't find how to save and load my model.And if  I save each child model in sklearn's method,how can I load the bagging model?

**Comment by shaypal5** [comment]
Did pickle-ing the whole object failed?

**Comment by tw200464tw** [comment]
Yeah,I have used joblib to save and load my model successfully.Thank you!!

**Comment by shaypal5** [comment]
That's good to hear. Thank you for updating me. :)
