### ISSUE TITLE
Bagging example needs to be updated

### ISSUE THREAD

**Issue by myoshimu** [pulearn/pulearn#7]
Following notebook needs some update
https://github.com/pulearn/pulearn/blob/master/notebooks/bagging_blobs.ipynb

(before)from pulearn import BaggingClassifierPU
(after)from pulearn import BaggingPuClassifier

(before) bc = BaggingClassifierPU(
(after) bc = BaggingPuClassifier(

**Comment by shaypal5** [comment]
Done. Thank you!  <3
