### ISSUE TITLE
ImportError: cannot import name 'ElkanotoPuClassifier'

### ISSUE THREAD

**Issue by lucy9383** [pulearn/pulearn#9]
Somehow I cannot import the classifier.  I double checked my code is following flake8.  I copy paste the example program and it still cannot run. I tried to uninstall and install the pulearn package several times and it still did not work.

The Python I am using 3.6.  

Do I miss something here?

Thanks,

**Comment by junronglau** [comment]
Hi, I encountered this error as well:

`Traceback (most recent call last):
  File "pipeline/defects_classifier.py", line 10, in <module>
    from models.pubagging_model import PuBaggingModel
  File "C:\Users\Admin\Documents\SchoolWork\Y3S2\FYP\Projects\product-defects-extraction\models\pubagging_model.py", line 1, in <module>
    from pulearn import BaggingPuClassifier
  File "C:\Users\Admin\anaconda3\envs\dvc\lib\site-packages\pulearn\__init__.py", line 12, in <module>
    from .bagging import (  # noqa: F401
  File "C:\Users\Admin\anaconda3\envs\dvc\lib\site-packages\pulearn\bagging.py", line 48, in <module>
    from sklearn.ensemble.base import BaseEnsemble, _partition_estimators
ModuleNotFoundError: No module named 'sklearn.ensemble.base'
`

What i did was to change the imports in C:\Users\Admin\anaconda3\envs\dvc\lib\site-packages\pulearn\bagging.py
from `from sklearn.ensemble.base import BaseEnsemble, _partition_estimators` to `from sklearn.ensemble._base import BaseEnsemble, _partition_estimators`

Im on sklearn 0.24.0

**Comment by shaypal5** [comment]
Hopefully fixed in `v0.0.7`.

I'm closing this in the meantime. Please reopen if this presists.
